Bird indicators chapter
NINAnor/ecosystemCondition pull request #159
Opened 2023-10-21 12:04 UTC by ChloeRN

Submitting the draft of the bird indicators chapter. 

This needs reviewing not just by @anders-kolstad or @DrMattG, but also by @DiegoPavonJordan to ensure that the scripts are doing what they should.

2023-10-21 12:06 UTC, ChloeRN commented
@anders-kolstad can you confirm that you are serious about wanting the final results in a wide format table, i.e. v_YYYY, sd_YYYY etc. should be **COLUMN NAMES** ?
I have implemented it that way but it just goes against everything I believe in 😜

2023-10-21 12:07 UTC, ChloeRN commented
@anders-kolstad and @DrMattG please also double-check the situation with the references. I don't think it's supposed to work when rendering single chapters, but please make sure it turns out correctly when rendering the book.

2023-10-23 11:51 UTC, anders-kolstad requested changes
See comment about missing data object

2023-10-23 11:55 UTC, anders-kolstad commented
Thank you @ChloeRN . I started looking at it now, but got stuck due to a missing file.

Also about the wide format. You could be right. The idea was not to repeat the geometry column in the sf data. In any case you are the only one actually making it to the export stage so far, so I think I will just hash the part of the code that exports the data and also remove any output files from the repo, and then think about output formating later. It should probably go on OSF anyway, and not to GitHub.

2023-10-23 12:06 UTC, ChloeRN commented
@anders-kolstad which data object is missing?

2023-10-23 12:59 UTC, anders-kolstad reviewed
I'm unable to review before I can locate the Trim data

2023-10-23 12:59 UTC, anders-kolstad commented on DRAFT_birdIndicators.Rmd
> +sppLists <- makeSpeciesLists(Trim_data = Trim_data, spp_DataPath = "temp/birdIndicators-main/data")
I cant find _Trim_data_ which is created on line 220 with eval=F but not stored anywhere that I can see.

2023-10-23 13:00 UTC, anders-kolstad commented on DRAFT_birdIndicators.Rmd
> +sppLists <- makeSpeciesLists(Trim_data = Trim_data, spp_DataPath = "temp/birdIndicators-main/data")
There, I added the review again. Not sure what happened...

2023-10-23 18:34 UTC, anders-kolstad commented
Removing [eval=F](https://github.com/NINAnor/ecosystemCondition/pull/159/commits/35390937dd104f1fec70e2ec46be8fc3d5715e9b) made new error apprear:

```
Error: nanodbc/nanodbc.cpp:1135: 01S00: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot open database "TOVTaksering" requested by the login. The login failed.  [Microsoft][ODBC SQL Server Driver]Invalid connection string attribute 
```

This arrises in `DBI::dbConnect()` under `downloadData_TRIM()`

2023-10-24 13:36 UTC, anders-kolstad commented
@ChloeRN , I tried again to run `downloadData_TRIM()` from RStudio Server and now I get his error

```
Error: nanodbc/nanodbc.cpp:1125: 00000: [FreeTDS][SQL Server]Login failed for user 'NINA\anders.kolstad'.  [FreeTDS][SQL Server]Cannot open database "TOVTaksering" requested by the login. The login failed.  [FreeTDS][SQL Server]Unable to connect to data source 
```

My used does not have access is seems.

2023-10-26 08:12 UTC, ChloeRN commented
I think that means you need to contact Roald Vang and ask for access permission.
Otherwise:
I only use the downloaded data to make the "sppLists" object in the bookdown. I could instead add and read in this file as a .rds in the script. Would that be better?

________________________________
From: Anders L. Kolstad ***@***.***>
Sent: Tuesday, October 24, 2023 3:36 PM
To: NINAnor/ecosystemCondition ***@***.***>
Cc: Chloé R. Nater ***@***.***>; Mention ***@***.***>
Subject: Re: [NINAnor/ecosystemCondition] Bird indicators chapter (PR #159)


@ChloeRN<https://github.com/ChloeRN> , I tried again to run downloadData_TRIM() from RStudio Server and now I get his error

Error: nanodbc/nanodbc.cpp:1125: 00000: [FreeTDS][SQL Server]Login failed for user 'NINA\anders.kolstad'.  [FreeTDS][SQL Server]Cannot open database "TOVTaksering" requested by the login. The login failed.  [FreeTDS][SQL Server]Unable to connect to data source


My used does not have access is seems.

—
Reply to this email directly, view it on GitHub<https://github.com/NINAnor/ecosystemCondition/pull/159#issuecomment-1777221118>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJGP7ABX2A6LU3LPQPKWINTYA677LAVCNFSM6AAAAAA6KDC5D6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZXGIZDCMJRHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-27 08:17 UTC, ChloeRN commented
Will do this at the start of next week.
________________________________
From: Anders L. Kolstad ***@***.***>
Sent: Friday, October 27, 2023 10:16 AM
To: NINAnor/ecosystemCondition ***@***.***>
Cc: Chloé R. Nater ***@***.***>; Mention ***@***.***>
Subject: Re: [NINAnor/ecosystemCondition] Bird indicators chapter (PR #159)


Yes, perhaps cache the output and bypass this whole issue. And add a note as well that you need read persmissions to the data base in order to run the code?

—
Reply to this email directly, view it on GitHub<https://github.com/NINAnor/ecosystemCondition/pull/159#issuecomment-1782495961>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJGP7AD4Y7UK7CISVN2ZJMTYBNUXXAVCNFSM6AAAAAA6KDC5D6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBSGQ4TKOJWGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-30 12:12 UTC, ChloeRN commented
@anders-kolstad I have now added the object `sppLists` as data and changed over to reading that in from folder instead of downloading the entire data from "Hekkefuglovervåkingen" to make it. 
Hopefully that will make the chapter compile for you.

2023-10-30 14:05 UTC, anders-kolstad approved these changes

2023-10-30 14:07 UTC, merged