add chapter median-summer-temp and rename generic chapter
NINAnor/ecosystemCondition pull request #31
Opened 2023-03-14 10:30 UTC by anders-kolstad

Move generic chapter to _General topics_ and add succinct chapter on _median summer temperature_. Also updated _bookdown.yml

2023-03-14 19:33 UTC, DrMattG requested changes

2023-03-14 19:33 UTC, DrMattG commented on climate_indicators_explained.Rmd
> +This chapters describes the development of a workflow for generating or preparing indicators based on interpolated climate data from [SeNorge](https://senorge.no/). I describe the process using dummy
"a specific indicator"

2023-03-14 19:33 UTC, DrMattG commented on medianSummerTemperature.Rmd
> +This chapters describes the workflow for an indicator describing the median summer temperature. For a more comprehensive documentaion on the development of the workflow itself, se [here](#climate-ind
"workflow itself, see..."

2023-03-15 07:51 UTC, anders-kolstad commented on climate_indicators_explained.Rmd
> +This chapters describes the development of a workflow for generating or preparing indicators based on interpolated climate data from [SeNorge](https://senorge.no/). I describe the process using dummy
fixed

2023-03-15 07:52 UTC, anders-kolstad commented on medianSummerTemperature.Rmd
> +This chapters describes the workflow for an indicator describing the median summer temperature. For a more comprehensive documentaion on the development of the workflow itself, se [here](#climate-ind
fixed

2023-03-24 09:47 UTC, anders-kolstad commented
Struggled a bit to get this to knit again. See #35

2023-03-24 09:48 UTC, merged

2023-03-24 09:48 UTC, anders-kolstad commented
I merged this myself, but someone should still review the old PR