Draft for Nature Index chapter
NINAnor/ecosystemCondition pull request #61
Opened 2023-08-23 09:01 UTC by ChloeRN

I have written a first draft for the Nature Index chapter. 
All code is function-based and using wrappers / helper functions I wrote in a new package NIflex (https://github.com/NINAnor/NIflex), so code review may have to include the package's repository as well. 

At the moment, the code needs NI database user credentials to be specified as environmental variables, so you will need to set this up individually to make it work. Siw and I are working on setting up a "dummy user" for the database, for which we can then add credentials as project environmental variables. 

On request of @HannoSandvik I am submitting this already now even though it is not completely finished so that code review can start.
I have a handful of additions to make before the chapter can be considered complete, but I will not have time to deal with these until September. They are: 

- [ ] Add table with overview of indicators that are part of NI Våtmark
- [ ] Add results of discussion on NI includion in ØT (discussion will involve me, @anders-kolstad, and @HannoSandvik)
- [ ] Add references
- [ ] Add function to make georeferenced end-product (will involve code already written for `NIflex::plotNI_Map()`

2023-09-04 13:20 UTC, ChloeRN commented
Included indicator overview in 45c01d2a042ba12160823b6e367d50520d0ba9f0

2023-09-05 06:03 UTC, ChloeRN commented
Final adjustments complete. 
The only thing missing is reporting the results of the discussion with @anders-kolstad and @HannoSandvik  (scheduled for October) and to update NIflex code accordingly.

2023-09-12 12:14 UTC, DrMattG requested changes

2023-09-12 12:14 UTC, DrMattG commented on .Renviron
> +NIDB_USRNAME="lesebruker@nina.no"
Check that it is okay that these are publically visable

2023-09-12 12:14 UTC, DrMattG commented on DRAFT_nature_index.Rmd
> +CustomNI_map <- geomapNI(Index = CustomNI$CustomIndex,
I get stuck here due to missing permissions on the folder (awaiting update from datahjelp) 
Quitting from lines 283-288 [unnamed-chunk-17] (DRAFT-Nature-Index-product.Rmd)
Error:
! Cannot open "/data/P-Prosjekter/41201611_naturindeks_2021_2023_vitenskapelig_ansvar/Shapefiles/NI_ecosystems/NI_ecosystem_Terrestrial"; The file doesn't seem to exist.

2023-09-13 14:24 UTC, DrMattG commented
I will close this here as I have rendered this chapter to the book using my own branch (should be available in 12 hours) and @HannoSandvik can review it next week.

2023-09-13 14:24 UTC, closed without merging