Trophic levels biomass mjg
NINAnor/ecosystemCondition pull request #66
Opened 2023-09-07 10:51 UTC by DrMattG

Updated James' pull request

2023-09-07 10:52 UTC, DrMattG commented
This superceeds the previous pull requests

2023-09-07 11:55 UTC, HannoSandvik commented on trophic_levels-biomass_indicators.rmd
Here the years are not visible in the headings of the 12 panels. Would be great to see them.

2023-09-07 11:58 UTC, HannoSandvik requested changes
I re-inserted by previous suggestions. Now I am fine with this version, except for my comment on the missing labels in the panels of one figure.

2023-09-08 10:51 UTC, DrMattG commented
Merging this now with changes to the plots suggested by @HannoSandvik

2023-09-08 10:51 UTC, merged